wandb_version: 1

workers:
  desc: null
  value: 5
world_size:
  desc: null
  value: 1
print_freq:
  desc: null
  value: 5
root:
  desc: null
  value: .
checkpoint_dir:
  desc: null
  value: checkpoint
load:
  desc: null
  value: false
start_epoch:
  desc: null
  value: 0
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 1.0e-05
momentum:
  desc: null
  value: 0.95
clip:
  desc: null
  value: 100
betas:
  desc: null
  value:
  - 0.9
  - 0.98
eps:
  desc: null
  value: 1.0e-09
lambd:
  desc: null
  value: 0.5
optimizer:
  desc: null
  value: adam
proj_dim:
  desc: null
  value: 512
text_encoder:
  desc: null
  value: bert-base-multilingual-uncased
mbert_out_size:
  desc: null
  value: 512
rank:
  desc: null
  value: 0
dist_url:
  desc: null
  value: tcp://localhost:58472
ngpus_per_node:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    code_path: code/pretrain_ectc.py
    python_version: 3.12.1
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.38.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712681902.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.12.1
      5: 0.16.6
      6: 4.38.1
      8:
      - 5
      - 9
      10:
      - 3
      13: linux-x86_64
